### ISSUE TITLE
Where is the code in src?

### ISSUE THREAD

**Issue by ahmadalibaloch** [xyzingh/EventNet#1]
I can't find code in files but only the version.

**Comment by FuuuOverclocking** [comment]
I am terribly sorry. Although having promised to develop as soon as possible, I’ve been very busy for recent few months and now I'm tired of dealing with the exams. You can download code by command `npm install eventnet`. But that version is unsound and totally different from what described in README.

The README is also out of date. I will write the latest structure out in July.
